name: Deploy to GitHub Pages

on:
  pull_request:
    types : [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./app/yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./app

      - name: Build
        run: yarn build
        working-directory: ./app

      - name: Export
        run: yarn export
        working-directory: ./app

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out
